apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
spec:
  destination:
    namespace: argocd
    name: in-cluster
  project: default
  source:
    path: argocd/
    repoURL: https://github.com/morey-tech/argocd-v2.9.0-examples.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true